esphome:
  name: lcd
  friendly_name: LCD

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "ReFbnDC05JxxJZVsb86EIQnaYrwBzL25AK+1/pgCgvY="

ota:
  - platform: esphome
    password: "2f109b22b920691a02f9ec73d9c7516a"

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Lcd Fallback Hotspot"
    password: "NGMso0wk9jQZ"

i2c:
  sda: GPIO21
  scl: GPIO23
  scan: true
  id: bus_a

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    update_interval: 500ms
    lambda: |-
      static int scroll2 = 0;

      // Riga fissa (prima riga - index 0)
      it.print(0, 0, "Fattelo da solo");

      // Riga scorrevole (terza riga - index 2)
      std::string line2 = "iscriviti al canale    ";  // Aggiungi spazi per pausa visiva
      it.print(0, 2, line2.substr(scroll2, 20).c_str());
      scroll2++;
      if (scroll2 >= line2.length() - 1) scroll2 = 0;
