esphome:
  name: lcd
  friendly_name: LCD

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "ReFbnDC05JxxJZVsb86EIQnaYrwBzL25AK+1/pgCgvY="

ota:
  - platform: esphome
    password: "2f109b22b920691a02f9ec73d9c7516a"

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Lcd Fallback Hotspot"
    password: "NGMso0wk9jQZ"

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27  # Cambia in 0x3F
    update_interval: 5s
    lambda: |-
      it.print(0, 0, "Fattelo da solo");
      it.print(0, 2, "iscriviti al canale");   
