esphome:
  name: bme280
  friendly_name: BME280

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "RfxHFeEhZJlnkO21+paQV9KltSF32WDWjRXKJWwL544="

ota:
  - platform: esphome
    password: "3a1bc630c824bfdb94aa9b27f7d56810"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 
  ap:
    ssid: "Bme280 Fallback Hotspot"
    password: "YSkytPDu84IB"

i2c:
  sda: GPIO4
  scl: GPIO0
  scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temperatura"
      oversampling: 16x
    pressure:
      name: "Pressione"
    humidity:
      name: "Umidità"
    address: 0x76  # 0x77 se il sensore ha un altro indirizzo
    update_interval: 2s

captive_portal:
    