esphome:
  name: mango
  friendly_name: Mango

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"


ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configurazione del sensore DHT11
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO14          # Pin D5 sul D1 Mini corrisponde a GPIO14
    temperature:
      name: "Temperatura"
      unit_of_measurement: "°C"
      accuracy_decimals: 0
    humidity:
      name: "Umidità"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    update_interval: 2s

  # Configurazione del sensore igrometro analogico
  - platform: adc
    pin: A0           # Pin analogico A0 sul D1 Mini
    name: "Umidità del Suolo"
    unit_of_measurement: "%"
    accuracy_decimals: 1
#   update_interval: 2s
    filters:
      - calibrate_linear:
         - 3.3 -> 0.0       # In aria
         - 0.1 -> 100.0      # Terreno moderatamente umido

deep_sleep:
  run_duration: 120s
  sleep_duration: 1200s