esphome:
  name: pulsante
  friendly_name: Pulsante

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "vHO6i0mxLvZrvlQ4BN6Pth7f3ggcHTACBfR5Hn2Xt4A="

ota:
  - platform: esphome
    password: "8b9e6eaff7c986c865a4912294f4c9d4"

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Pulsante Fallback Hotspot"
    password: "V4zTkJyydloY"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Raw Button"
    id: raw_button

    # Singolo e doppio click
    on_multi_click:
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 100ms
        then:
          - text_sensor.template.publish:
              id: button_event
              state: "single_click"

      - timing:
          - ON for 50ms to 350ms
          - OFF for 50ms to 350ms
          - ON for 50ms to 350ms
        then:
          - text_sensor.template.publish:
              id: button_event
              state: "double_click"

    # Pressione lunga
    on_press:
      - script.execute: long_press_script
    on_release:
      - script.stop: long_press_script

script:
  - id: long_press_script
    mode: restart
    then:
      - delay: 1.5s
      - text_sensor.template.publish:
          id: button_event
          state: "long_press"

text_sensor:
  - platform: template
    name: "Button Event"
    id: button_event
    update_interval: never
