esphome:
  name: aj-sr04m
  friendly_name: AJ-SR04M

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "cWEiSBVWcthRadkAQkTWRw/qmGHgPFPHsVmwJyGH/BU="

captive_portal:

ota:
  - platform: esphome
    password: "1f7c6ea7300729258a51f5e14fe8694d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Aj-Sr04M Fallback Hotspot"
    password: "c7aQxajFGzAb"

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO4
    echo_pin: GPIO0
    name: "Distanza AJ-SR04M"
    update_interval: 1s
    timeout: 3m
    unit_of_measurement: "m"
    
